/**
 * Some colors have been rearranged from their default Wc3 positions.
 * This is done to prevent using similar colors when not needed (small games)
 * Snow 22, Turquoise 15, Mint 19, Navy 14, Emerald 23, Coal 20
 */
export const PLAYER_COLORS = [
    PLAYER_COLOR_RED,
    PLAYER_COLOR_BLUE,
    PLAYER_COLOR_CYAN,
    PLAYER_COLOR_PURPLE,
    PLAYER_COLOR_YELLOW,
    PLAYER_COLOR_ORANGE,
    PLAYER_COLOR_GREEN,
    PLAYER_COLOR_PINK,
    PLAYER_COLOR_LIGHT_GRAY,
    PLAYER_COLOR_LIGHT_BLUE,
    PLAYER_COLOR_AQUA,
    PLAYER_COLOR_BROWN,
    PLAYER_COLOR_MAROON,
    PLAYER_COLOR_VIOLET,
    PLAYER_COLOR_WHEAT,
    PLAYER_COLOR_PEACH,
    PLAYER_COLOR_LAVENDER,
    PLAYER_COLOR_PEANUT,
    //Swapped Colors
    PLAYER_COLOR_COAL,
    PLAYER_COLOR_EMERALD,
    PLAYER_COLOR_NAVY,
    PLAYER_COLOR_MINT,
    PLAYER_COLOR_TURQUOISE,
    //PLAYER_COLOR_SNOW,
];

export const PLAYER_COLOR_CODES = [
    "|cffff0303",
    "|cff0042ff",
    "|cff1be7ba",
    "|cff550081",
    "|cfffefc00",
    "|cfffe890d",
    "|cff21bf00",
    "|cffe45caf",
    "|cff939596",
    "|cff77bbff",
    "|cff106247",
    "|cff4f2b05",
    "|cff9c0000",
    "|cffbd00ff",
    "|cffecce87",
    "|cfff7a58b",
    "|cffdbb8eb",
    "|cffa56f34",
    //Swapped Colors
    "|cff4f5055",
    "|cff00781e",
    "|cff0000c3",
    "|cffccff99",
    "|cff00ebff",
    //"|cffecf0ff",
]

export const PLAYER_COLOR_NAMES = [
    "Red",
    "Blue",
    "Teal",
    "Purple",
    "Yellow",
    "Orange",
    "Green",
    "Pink",
    "Gray",
    "Light Blue",
    "Dark Green",
    "Brown",
    "Maroon",
    "Violet",
    "Wheat",
    "Peach",
    "Lavender",
    "Peanut",
    //Swapped Colors
    "Coal",
    "Emerald",
    "Navy",
    "Mint",
    "Turquoise",
    //"Snow",
]

export const OG_PLAYER_COLORS = {
    RED: PLAYER_COLOR_RED,
    BLUE: PLAYER_COLOR_BLUE,
    CYAN: PLAYER_COLOR_CYAN,
    PURPLE: PLAYER_COLOR_PURPLE,
    YELLOW: PLAYER_COLOR_YELLOW,
    ORANGE: PLAYER_COLOR_ORANGE,
    GREEN: PLAYER_COLOR_GREEN,
    PINK: PLAYER_COLOR_PINK,
    LIGHT_GRAY: PLAYER_COLOR_LIGHT_GRAY,
    LIGHT_BLUE: PLAYER_COLOR_LIGHT_BLUE,
    AQUA: PLAYER_COLOR_AQUA,
    BROWN: PLAYER_COLOR_BROWN,
    MAROON: PLAYER_COLOR_MAROON,
    NAVY: PLAYER_COLOR_NAVY,
    TURQUOISE: PLAYER_COLOR_TURQUOISE,
    VIOLET: PLAYER_COLOR_VIOLET,
    WHEAT: PLAYER_COLOR_WHEAT,
    PEACH: PLAYER_COLOR_PEACH,
    MINT: PLAYER_COLOR_MINT,
    LAVENDER: PLAYER_COLOR_LAVENDER,
    COAL: PLAYER_COLOR_COAL,
    SNOW: PLAYER_COLOR_SNOW,
    EMERALD: PLAYER_COLOR_EMERALD,
    PEANUT: PLAYER_COLOR_PEANUT
};

export const OG_PLAYER_COLOR_CODES = {
    RED: "|cffff0303",
    BLUE: "|cff0042ff",
    CYAN: "|cff1be7ba",
    PURPLE: "|cff550081",
    YELLOW: "|cfffefc00",
    ORANGE: "|cfffe890d",
    GREEN: "|cff21bf00",
    PINK: "|cffe45caf",
    LIGHT_GRAY: "|cff939596",
    LIGHT_BLUE: "|cff77bbff",
    AQUA: "|cff106247",
    BROWN: "|cff4f2b05",
    MAROON: "|cff9c0000",
    NAVY: "|cff0000c3",
    TURQUOISE: "|cff00ebff",
    VIOLET: "|cffbd00ff",
    WHEAT: "|cffecce87",
    PEACH: "|cfff7a58b",
    MINT: "|cffccff99",
    LAVENDER: "|cffdbb8eb",
    COAL: "|cff4f5055",
    SNOW: "|cffecf0ff",
    EMERALD: "|cff00781e",
    PEANUT: "|cffa56f34"
}

export const OG_PLAYER_COLOR_NAMES = {
    RED: "Red",
    BLUE: "Blue",
    CYAN: "Teal",
    PURPLE: "Purple",
    YELLOW: "Yellow",
    ORANGE: "Orange",
    GREEN: "Green",
    PINK: "Pink",
    LIGHT_GRAY: "Gray",
    LIGHT_BLUE: "Light Blue",
    AQUA: "Dark Green",
    BROWN: "Brown",
    MAROON: "Maroon",
    NAVY: "Navy",
    TURQUOISE: "Turquoise",
    VIOLET: "Violet",
    WHEAT: "Wheat",
    PEACH: "Peach",
    MINT: "Mint",
    LAVENDER: "Lavender",
    COAL: "Coal",
    SNOW: "Snow",
    EMERALD: "Emerald",
    PEANUT: "Peanut"
}

export const pingRedPercent = [
    100.00,
    0.00,
    10.98,
    32.94,
    100.00,
    99.61,
    12.55,
    89.80,
    58.43,
    49.41,
    6.27,
    29.02,
    60.78,
    0.00,
    0.00,
    74.51,
    92.16,
    97.25,
    74.90,
    86.27,
    15.69,
    92.16,
    0.00,
    64.31
];

export const pingGreenPercent = [
    1.18,
    25.88,
    90.20,
    0.00,
    98.82,
    54.12,
    75.29,
    35.69,
    58.82,
    74.90,
    38.43,
    16.47,
    0.00,
    0.00,
    91.76,
    0.00,
    80.39,
    64.31,
    100.00,
    72.55,
    15.69,
    94.12,
    47.06,
    43.53
];

export const pingBluePercent = [
    1.18,
    100.00,
    72.55,
    50.59,
    0.00,
    5.49,
    0.00,
    69.02,
    59.22,
    94.51,
    27.45,
    1.57,
    0.00,
    76.47,
    100.00,
    99.61,
    52.94,
    54.51,
    50.20,
    92.16,
    15.69,
    100.00,
    11.76,
    20.00
];