export const UTYPE = {
	SPAWN: UNIT_TYPE_UNDEAD,
	GUARD: UNIT_TYPE_SAPPER,
	SHIP: UNIT_TYPE_GIANT,
	CITY: UNIT_TYPE_TOWNHALL,
	BUILDING: UNIT_TYPE_STRUCTURE,
	TRANSPORT: UNIT_TYPE_ANCIENT,
	ARTILLERY: UNIT_TYPE_TAUREN,
}